In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('candies.csv')
df

     color  shape  package
0    green  round    False
1   yellow  round    False
2   yellow  round    False
3   yellow  round    False
4   yellow  round    False
5   yellow  round    False
6      red  round    False
7   orange  round    False
8    brown  round    False
9    brown  round    False
10   green   bear    False
11     red   bear    False
12   white   bear    False
13  yellow   bear    False
14  orange   bear    False
15  yellow   bear    False
16    gold  round     True
17    gold  round     True
18    gold  round     True

Sort once: Find a single rule to separate all the candies into two groups.

In [15]:
df.groupby(by=['package']).count()

         color  shape
package
False       16     16
True         3      3

Optimal sort: In the fewest rules possible, separate each candy into the correct type M&M, Skittle, etc.

     color  shape  package
0    green  round    False
1   yellow  round    False
2   yellow  round    False
3   yellow  round    False
4   yellow  round    False
5   yellow  round    False
6      red  round    False
7   orange  round    False
8    brown  round    False
9    brown  round    False
10   green   bear    False
11     red   bear    False
12   white   bear    False
13  yellow   bear    False
14  orange   bear    False
15  yellow   bear    False
16    gold  round     True
17    gold  round     True
18    gold  round     True